### ISSUE TITLE
Crash when running the fbcunn imagenet example

### ISSUE THREAD

**Issue by rbjarnason** [facebook/fbnn#3]
```
/home/ubuntu/torch-distro/install/bin/luajit: ...ubuntu/torch-distro/install/share/lua/5.1/fbnn/Optim.lua:61: attempt to call method 'for_each' (a nil value)
stack traceback:
	...ubuntu/torch-distro/install/share/lua/5.1/fbnn/Optim.lua:61: in function '__init'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/init.lua:50: in function <...ubuntu/torch-distro/install/share/lua/5.1/torch/init.lua:46>
	[C]: in function 'Optim'
	/home/ubuntu/fbcunn/examples/imagenet/train.lua:35: in main chunk
```

Any ideas?

**Comment by soumith** [comment]
```bash
git clone https://github.com/torch/nn && cd nn && git checkout getParamsByDevice && luarocks make rocks/nn-scm-1.rockspec
```
will fix it. It is specified in INSTALL.md of fbcunn.

**Comment by rbjarnason** [comment]
Thanks for a quick reply, it worked, has started the training :)

**Comment by Atcold** [comment]
@soumith, when will this be integrated into `main`?

**Comment by soumith** [comment]
@Atcold if you noticed, I've removed the fbcunn imagenet example altogether and have changed the imagenet-multiGPU example to nn.DataParallelTable (which is already integrated in master). Overall, I think that seems to be a better approach than adding an additional layer of abstraction like nn.Optim and magic under the hood.

**Comment by Atcold** [comment]
@soumith, no I did see it. Thank you for pointing it out. I will pull your `HEAD` (git-wise, of course) :grin:
(I'm also facing some `/usr/local/bin/luajit: not enough memory` errors after the first testing. I see if I can figure out what's bad...)
